version: "3.6"

services:
  app:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - "TZ=Asia/Shanghai"
      - "REACT_NATIVE_PACKAGER_HOSTNAME=47.114.148.207"
      - "EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0"
