site_name: Visit Link App Documentation
site_description: This site represents the documentation for the Visit Link App.

theme:
  name: material

nav:
  - Home: index.md
  - Publish Guide: publish.md

docs_dir: docs
site_dir: site
